import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppinsLight = Poppins({
  variable: '--font-poppins',
  subsets: ['devanagari'],
  weight: ['300']
})


const poppinsBlack = Poppins({
  variable: '--font-poppinsBlack',
  subsets: ['devanagari'],
  weight: ['900']
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CodeQuest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppinsLight.variable} ${poppinsBlack.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
